apiVersion: v1
kind: ConfigMap
metadata:
  name: site-conf
  namespace: elasticsearch
data:
  site.conf: |
    server_tokens off;
    server {
        listen       80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    		location /search/ {
            auth_basic "Restricted";
            auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
            proxy_pass    http://localhost:9200/;
    		}
    }
  .htpasswd: |
    elastic:$apr1$j9XW7Exl$UXT8KyvzAQNLuykml09HY/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-top-html
  namespace: elasticsearch
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>elasticsearch-sample</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
        }
    </style>
    </head>
    <body>
    <h1>HealthCheck OK!</h1>

    <p>elasticsearch is <a href="/search">here</a></p>

    </body>
    </html>
